Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

In [4]:
import numpy as np

arr1 = np.array([2,4,6,8,9])
arr2 = arr1+2
print(arr2)
arr3 = arr1*3
print(arr3)
arr4 = arr1/2
print(arr4)


[ 4  6  8 10 11]
[ 6 12 18 24 27]
[1.  2.  3.  4.  4.5]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [6]:
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_valuex = np.bincount(x).argmax()
most_freq_valuey = np.bincount(y).argmax()
indicex = np.where(x == most_freq_valuex)[0]
indicey = np.where(y == most_freq_valuex)[0]
print("Most Frequent Value in x:", most_freq_valuex)
print("Indices of Most Frequent Value:", indicex)
print("Most Frequent Value in y:", most_freq_valuey)
print("Indices of Most Frequent Value:", indicey)

[5 4 6 3 2 1]
Most Frequent Value in x: 1
Indices of Most Frequent Value: [0 5 7 8 9]
Most Frequent Value in y: 1
Indices of Most Frequent Value: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [7]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [8]:
vishesh= np.linspace(10,100,25)
print(f'The array formed :{vishesh}')
print(f'Dimensions :{vishesh.ndim}')
print(f'Shape: {vishesh.shape}')
print(f'Elements: {vishesh.size}')
print(f'Data type :{vishesh.dtype}')
print(f'Bytes per elements: {vishesh.itemsize}')
print(f'Total bytes: {vishesh.itemsize * vishesh.size}')
print(f'Reshaped :{vishesh.reshape(25,1)}')

print(vishesh.reshape(25,1).T)

The array formed :[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions :1
Shape: (25,)
Elements: 25
Data type :float64
Bytes per elements: 8
Total bytes: 200
Reshaped :[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]


Q5.  Create a 2-D Array of three rows and four columns, named ucs420_<\your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements.

 Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<\your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<\your_name>>.

In [9]:
ucs420_vishesh = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])
ucs420_vishesh = ucs420_vishesh.reshape(3,4)
print(f'Original :{ucs420_vishesh}')

print(f'Mean: {np.mean(ucs420_vishesh)}')
print(f'Median: {np.median(ucs420_vishesh)}')
print(f'Max: {np.max(ucs420_vishesh)}')
print(f'Min: {np.min(ucs420_vishesh)}')

x,y=np.unique(ucs420_vishesh, return_counts= True)
print(f'Unique Elements: {x}')
print(f'Their count: {y}')

reshaped_ucs420_vishesh = ucs420_vishesh.reshape(4,3)
print(f'Reshaped : {reshaped_ucs420_vishesh}')
resized_ucs420_vishesh = ucs420_vishesh.copy()
resized_ucs420_vishesh.resize(2, 3)
print(f'Resized: {resized_ucs420_vishesh}')

Original :[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Their count: [1 1 2 1 1 1 1 1 1 1 1]
Reshaped : [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized: [[10 20 30]
 [40 50 60]]
